name: Greetings

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello ${{ github.actor }}, Thank you for raising this issue! 😊 Your contribution is valuable to us! 😊 \n\n - Please make sure to follow our [Contributing Guidelines. 💪🏻](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md) \n\n - Please only work on an issue if you're assigned; otherwise, the PR will be automatically closed.\n\n - Our review team will carefully assess the issue and reach out to you soon! 😇 \n\n - We appreciate your patience! "
          pr-message: "Thank you, ${{ github.actor }}, for creating this pull request and contributing to HelpOps-Hub! 💗\n\n The maintainers will review this Pull Request and provide feedback as soon as possible! 😇\n\n - We appreciate your patience and contribution, Keep up the great work! 😀"
